version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./site:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - php
      - mariadb

  php:
    build:
      context: .
    env_file: .env
    container_name: php
    volumes:
      - ./site:/var/www/html

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
    ports:
      - 3306:3306
